{
    'name': 'Maeknit Manufacturing Customization',
    'description': 'Customize Manufacturing with BOM data',
    'summary': 'Enhanced Manufacturing for Maeknit',
    'version': '1.6.4',
    'depends': [ 'web', 'base', 'mail', 'mrp', 'mrp_workorder', 'stock', 'quality', 'maeknit_inventory_customization'],

    'author': 'Mahimul Islam (MAEKNIT)',
    'category': 'Manufacturing',
    'data': [
        'security/ir.model.access.csv',
        'data/toile_service_data.xml',
        'report/mfg_sheet_report.xml',
        "views/shopfloor_operation_views.xml",
        'views/mrp_program_files_wizard_views.xml',
        'views/reknit_wizard_views.xml',
        'views/bom_operation_template_views.xml',
        'views/bom_rnd_task_template_views.xml',
        'views/workorder_attachment_wizard_views.xml',
        'views/calibration_swatch_confirm_wizard_views.xml',
        'views/stitch_density_wizard_views.xml',
        'views/whole_cad_measurement_wizard_views.xml',
        'views/toile_doc_wizard_views.xml',
        'views/workorder_restart_wizard_views.xml',
        'views/request_new_program_wizard_views.xml',
        'views/produce_all_update_wizard_views.xml',
        'views/render_image_line_views.xml',
        'views/mrp_services_menu_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_workcenter_views.xml',
        'views/mail_message_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'maeknit_mfg_customization/static/src/css/manufacturing.css',
            'maeknit_mfg_customization/static/src/css/render_image_lightbox.css',
            'maeknit_mfg_customization/static/src/css/calibration_widget.css',
            'maeknit_mfg_customization/static/src/js/components/mrp_production_owl_widget.js',
            'maeknit_mfg_customization/static/src/xml/mrp_production_owl_widget.xml',
            "maeknit_mfg_customization/static/src/js/components/mrp_workorder.js",
            "maeknit_mfg_customization/static/src/js/dialog/mrp_program_files_dialog.js",
            "maeknit_mfg_customization/static/src/js/components/mrp_programs.js",
            'maeknit_mfg_customization/static/src/xml/mrp_worksheet.xml',
            "maeknit_mfg_customization/static/src/js/components/mrp_display_menu_patch.js",
            "maeknit_mfg_customization/static/src/xml/mrp_display_menu_patch.xml",
            "maeknit_mfg_customization/static/src/js/components/mrp_display_record_patch.js",
            "maeknit_mfg_customization/static/src/xml/mrp_display_record_patch.xml",
            "maeknit_mfg_customization/static/src/js/components/download_attachments.js",
            "maeknit_mfg_customization/static/src/js/components/workorder_chatter.js",
            "maeknit_mfg_customization/static/src/xml/workorder_chatter.xml",
            'maeknit_mfg_customization/static/src/js/components/calibration_widget.js',
            'maeknit_mfg_customization/static/src/xml/calibration_widget.xml',
            'maeknit_mfg_customization/static/src/js/components/render_image_lightbox.js',
            'maeknit_mfg_customization/static/src/js/fields/excalidraw_reprogram_field.js',
            'maeknit_mfg_customization/static/src/xml/fields/excalidraw_reprogram_field.xml',
            'maeknit_mfg_customization/static/src/js/workorder_list_renderer_patch.js',
        ]
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'website': 'https://maeknit.com',
}
