{
    'name': 'Maeknit Sales Customization',
    'version': '1.1.3',
    'summary': 'Make Studio Lead Name field editable in Quotations list view',
    'description': 'Overrides a Studio-created related field to allow inline editing in the tree view.',
    'category': 'Sales',
    'author': 'Mahimul Islam (Maeknit)',
    'website': 'https://maeknit.io',
    'depends': ['base', 'project', 'project_enterprise', 'hr_timesheet', 'sale_timesheet', 'sale', 'mrp', 'mail', 'web', 'website', 'maeknit_crm_customization', 'maeknit_inventory_customization', 'maeknit_mfg_customization', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/bom_request_security.xml',
        'data/ir_sequence.xml',
        'views/bom_duplicate_wizard_views.xml',
        'views/bom_request_views.xml',
        'views/sale_order_view.xml',
        'views/sale_order_form_view.xml',
        'views/sale_order_line_views.xml',
        'views/revision_request_wizard_views.xml',
        'views/operation_attachment_wizard_views.xml',
        'views/client_attachment_wizard_views.xml',
        'views/grading_size_wizard_views.xml',
        'views/grading_wizard_views.xml',
        'views/project_task_views.xml',
        'views/production_ready_wizard_views.xml',
        'views/report_invoice.xml',
        'views/stock_move_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'maeknit_sales_customization/static/description/icon.png',
            'maeknit_sales_customization/static/src/css/badge.css',
            'maeknit_sales_customization/static/src/js/measurement_sheet_widget.js',
            'maeknit_sales_customization/static/src/xml/measurement_sheet_widget.xml',
            'maeknit_sales_customization/static/src/css/measurement_sheet_widget.css',
            'maeknit_sales_customization/static/src/js/whole_cad_widget.js',
            'maeknit_sales_customization/static/src/xml/whole_cad_widget.xml',
            'maeknit_sales_customization/static/src/css/whole_cad_widget.css',
            'maeknit_sales_customization/static/src/js/artwork_widget.js',
            'maeknit_sales_customization/static/src/xml/artwork_widget.xml',
            'maeknit_sales_customization/static/src/css/artwork_widget.css',
            'maeknit_sales_customization/static/src/js/timer_widget.js',
            'maeknit_sales_customization/static/src/xml/timer_widget.xml',
            'maeknit_sales_customization/static/src/css/yarn_orchestration.css',
            'maeknit_sales_customization/static/src/xml/tax_totals_patch.xml',
            'maeknit_sales_customization/static/src/js/price_calculator_widget.js',
            'maeknit_sales_customization/static/src/xml/price_calculator_widget.xml',
            'maeknit_sales_customization/static/src/css/price_calculator_widget.css',
            'maeknit_sales_customization/static/src/js/toile_doc_widget.js',
            'maeknit_sales_customization/static/src/xml/toile_doc_widget.xml',
            'maeknit_sales_customization/static/src/xml/variant_picker_dialog.xml',
            'maeknit_sales_customization/static/src/js/sale_product_field_patch.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
