{
    'name': 'Maeknit Shipstation Shipping Integration',
    'version': '1.0.1',
    'author': "Maeknit Inc",
    'license': 'OPL-1',
    'category': "Website",
    'summary': "Odoo Shipstation Shipping Integration",
    'website': 'https://www.maeknit.com',
    'description': "Shipstation Shipping Integration with Odoo",
    'depends': ['delivery','stock','stock_delivery','sale_stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/product_demo.xml',
        'view/shipstation_odoo_integration_config.xml',
        'view/shipstation_store_view.xml',
        'view/shipstaion_operation_detail.xml',
        'view/shipstation_delivery_carrier.xml',
        'view/shipstation_delivery_carrier_service.xml',
        'view/delivery_carrier.xml',
        'view/shipstation_delivery_carrier_package.xml',
        'view/stock_picking.xml',
        'view/stock_quant.xml',
        'view/sale_order.xml',
        'view/stock_warehouse.xml',
        'view/shipstaion_warehouse_detail.xml',
        'view/shipstation_carrier_selection_wizard.xml',
        'view/shipstation_put_in_pack_wizard.xml',
        'view/shipstation_generate_labels_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'shipstation_shipping_odoo_integration/static/src/js/**/*.js',
            'shipstation_shipping_odoo_integration/static/src/xml/**/*.xml',
            'shipstation_shipping_odoo_integration/static/src/scss/**/*.scss',
        ],
    },
    'images': [
        'static/description/cover.gif',
    ],
    'demo': [],
    'post_init_hook': '_ensure_shipstation_carrier_active',
    'installable': True,
    'auto_install': False,
    'application': True,
}
