{
    'name': 'MAEKNIT CRM Customization',
    'description': 'Customize CRM Templates with OWL',
    'summary': 'Customize the CRM Module',
    'version': '1.0',
    'category': 'Customization',
    'depends': ['web', 'crm', 'sale_crm', 'product', 'maeknit_inventory_customization', 'maeknit_contact_customization'],
    'data': [
        'security/ir.model.access.csv',
        'data/crm_lead_sequence.xml',
        'data/swatch_sequence.xml',
        'data/style_family_sequence.xml',
        'views/crm_lead_kanban_view.xml',
        'views/crm_lead_views.xml',
        'views/crm_stage_views.xml',
        'views/crm_lead_quote_confirm_view.xml',
        'views/crm_lead_existing_quote_warning_view.xml',
        'views/crm_lead_variant_wizard_view.xml',
        'views/res_partner_quick_create.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'maeknit_crm_customization/static/src/css/crm_lead_form.css',
            'maeknit_crm_customization/static/src/js/utils/form_data_manager.js',
            'maeknit_crm_customization/static/src/js/utils/helpers.js',
            'maeknit_crm_customization/static/src/js/utils/service_manager.js',
            'maeknit_crm_customization/static/src/js/components/crm_lead_widget.js',
            'maeknit_crm_customization/static/src/js/crm_lead_form.js',
            'maeknit_crm_customization/static/src/js/managers/child_opportunities_manager.js',
            'maeknit_crm_customization/static/src/js/managers/data_manager.js',
            'maeknit_crm_customization/static/src/js/managers/development_tab_manager.js',
            'maeknit_crm_customization/static/src/js/managers/form_input_manager.js',
            'maeknit_crm_customization/static/src/js/managers/grading_tab_manager.js',
            'maeknit_crm_customization/static/src/js/managers/onboarding_tab_manager.js',
            'maeknit_crm_customization/static/src/js/managers/production_tab_manager.js',
            'maeknit_crm_customization/static/src/js/managers/reverse_tab_manager.js',
            'maeknit_crm_customization/static/src/js/managers/search_dropdown_manager.js',
            'maeknit_crm_customization/static/src/js/managers/swatching_tab_manager.js',
            'maeknit_crm_customization/static/src/xml/crm_lead_form.xml',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'author': 'Mahimul Islam (Maeknit)',
    'website': 'https://maeknit.com',
}
