from . import product_template
from . import product_product
from . import product_fiber
from . import product_color
from . import machine_library
from . import gauge_library
from . import mrp_bom
from . import mrp_bom_line
from . import yarn_stock
from . import yarn_programming
from . import fiber_type
from . import fiber_category
from . import ir_actions
from . import sale_order_line
from . import stitch_library
from . import product_attribute_value
from . import sync_categories
from . import style_colorway
from . import style_size
from . import stock_move
from . import style_yarn_variant
from . import purchase_order_line
from . import stock_quant
from . import wash_library
from . import dry_library
