from . import mrp_production
from . import stock_rule
from . import shopfloor_operation
from . import mrp_workorder
from . import rnd_task_template
from . import bom_operation_template
from . import ir_attachment
from . import mrp_workcenter
from . import quality_alert
from . import render_image_line